"""empty message

Revision ID: 4e55f7016a73
Revises: fc3b8b8d858e
Create Date: 2020-06-29 22:40:14.254946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e55f7016a73'
down_revision = 'fc3b8b8d858e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'car', 'model', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    # ### end Alembic commands ###
