"""empty message

Revision ID: 65cf6ca6baec
Revises: 6bcf6323f738
Create Date: 2020-06-30 02:13:21.600270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cf6ca6baec'
down_revision = '6bcf6323f738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'car', 'location', ['base_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    # ### end Alembic commands ###
